### ISSUE TITLE
Running the examples result in 'bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress'

### ISSUE THREAD

**Issue by rossbeazley** [thetestgame/pyDroidDepot#2]
hey,

i was trying to validate my setup by running the  examples but they all throw the error in the title, eg

```
$ python3 talk.py 

Traceback (most recent call last):
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/talk.py", line 40, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/talk.py", line 16, in main
    d = await discover_droid(retry=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/../droiddepot/connection.py", line 324, in discover_droid
    discovered_droids = await discover_droids(retry)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/../droiddepot/connection.py", line 276, in discover_droids
    await scanner.start()
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/__init__.py", line 198, in start
    await self._backend.start()
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 185, in start
    self._stop = await manager.active_scan(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 416, in active_scan
    assert_reply(reply)
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
```

help be obi-wan, you're my only hope!
or Jordan Maxwell, you can help as well!

**Comment by rossbeazley** [comment]
additionally here are some logs after enabling bluez with debug

```
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:set_discovery_filter() sender :1.92
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:parse_discovery_filter_dict() filtered discovery params: transport: 6 rssi: 32767 pathloss: 32767  duplicate data: false discoverable false pattern (null)
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:set_discovery_filter() successfully pre-set filter
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:start_discovery() sender :1.92
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:update_discovery_filter()
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:discovery_filter_to_mgmt_cp()
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:trigger_start_discovery()
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:cancel_passive_scanning()
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:start_discovery_timeout()
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:start_discovery_timeout() adapter->current_discovery_filter == 1
Dec 26 22:10:45 galactica bluetoothd[15867]: src/adapter.c:start_discovery_timeout() sending MGMT_OP_START_SERVICE_DISCOVERY 127, 6, 0
Dec 26 22:10:45 galactica bluetoothd[15867]: src/shared/mgmt.c:send_request() [0x0000] command 0x003a
Dec 26 22:10:49 galactica bluetoothd[15867]: src/shared/mgmt.c:can_read_data() [0x0000] command 0x003a complete: 0x05
Dec 26 22:10:49 galactica bluetoothd[15867]: src/adapter.c:start_discovery_complete() status 0x05
Dec 26 22:10:49 galactica bluetoothd[15867]: src/adapter.c:discovery_remove() owner :1.92
Dec 26 22:10:49 galactica bluetoothd[15867]: src/adapter.c:discovery_disconnect() owner :1.92
Dec 26 22:10:49 galactica bluetoothd[15867]: src/adapter.c:discovery_remove() owner :1.92
Dec 26 22:10:49 galactica bluetoothd[15867]: src/adapter.c:discovery_free() 0x5579e29935d0
Dec 26 22:10:49 galactica bluetoothd[15867]: src/adapter.c:trigger_passive_scanning()
```

and from enabling logging in bleak

```
$ python3 talk.py 

2023-12-26 22:17:57,320 bleak.backends.bluezdbus.manager MainThread DEBUG: initial properties: {'/org/bluez': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.AgentManager1': {}, 'org.bluez.ProfileManager1': {}, 'org.bluez.HealthManager1': {}}, '/org/bluez/hci0': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Adapter1': {'Address': '14:F6:D8:A2:F4:26', 'AddressType': 'public', 'Name': 'galactica', 'Alias': 'galactica', 'Class': 1048844, 'Powered': True, 'Discoverable': False, 'DiscoverableTimeout': 180, 'Pairable': True, 'PairableTimeout': 0, 'Discovering': False, 'UUIDs': ['0000110e-0000-1000-8000-00805f9b34fb', '00001200-0000-1000-8000-00805f9b34fb', '00001132-0000-1000-8000-00805f9b34fb', '00001133-0000-1000-8000-00805f9b34fb', '0000110c-0000-1000-8000-00805f9b34fb', '00001800-0000-1000-8000-00805f9b34fb', '0000112f-0000-1000-8000-00805f9b34fb', '00001801-0000-1000-8000-00805f9b34fb', '00001106-0000-1000-8000-00805f9b34fb', '0000180a-0000-1000-8000-00805f9b34fb', '00001104-0000-1000-8000-00805f9b34fb', '00001105-0000-1000-8000-00805f9b34fb', '00005005-0000-1000-8000-0002ee000001'], 'Modalias': 'usb:v1D6Bp0246d0542', 'Roles': ['central', 'peripheral']}, 'org.freedesktop.DBus.Properties': {}, 'org.bluez.GattManager1': {}, 'org.bluez.Media1': {'SupportedUUIDs': ['0000110a-0000-1000-8000-00805f9b34fb', '0000110b-0000-1000-8000-00805f9b34fb']}, 'org.bluez.NetworkServer1': {}, 'org.bluez.LEAdvertisingManager1': {'ActiveInstances': 0, 'SupportedInstances': 6, 'SupportedIncludes': ['tx-power', 'appearance', 'local-name'], 'SupportedSecondaryChannels': ['1M', '2M', 'Coded']}}, '/org/bluez/hci0/dev_EA_E6_CD_47_29_84': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.Device1': {'Address': 'EA:E6:CD:47:29:84', 'AddressType': 'random', 'Name': 'DROID', 'Alias': 'DROID', 'Paired': False, 'Bonded': False, 'Trusted': False, 'Blocked': False, 'LegacyPairing': False, 'Connected': False, 'UUIDs': [], 'Adapter': '/org/bluez/hci0', 'ServicesResolved': False}, 'org.freedesktop.DBus.Properties': {}}}
Traceback (most recent call last):
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/talk.py", line 40, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/talk.py", line 16, in main
    d = await discover_droid(retry=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/../droiddepot/connection.py", line 324, in discover_droid
    discovered_droids = await discover_droids(retry)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/src/pyDroidDepot/examples/../droiddepot/connection.py", line 275, in discover_droids
    async with BleakScanner() as scanner:      
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/__init__.py", line 158, in __aenter__
    await self._backend.start()
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/backends/bluezdbus/scanner.py", line 185, in start
    self._stop = await manager.active_scan(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/backends/bluezdbus/manager.py", line 416, in active_scan
    assert_reply(reply)
  File "/home/rdlb/workspace/droiddepot/lib/python3.11/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
```

**Comment by githubdex59** [comment]
I get the same error, im using Ubuntu 22.04 with a Ryzon 5 3400G CPU and an nvidia 2060 TI GPU

**Comment by thetestgame** [comment]
Sorry it took me so long to circle back to this. I should I have a patch ready to go soon.

**Comment by thetestgame** [comment]
Should be fixed in the next version
